### PR TITLE
Added parameter loading function and data length specification function.

### PR DESCRIPTION
**Pull request by tomoyaf**
Added parameter loading function and data length specification function.
Also change the value of variable discriminator.trainable from False to True

### CODE REVIEW

**Comment by lukedeo** [comment]
Hi @tomoyaf, what's the overall purpose here?

**Comment by tomoyaf** [comment]
Hi @lukedeo, there are roughly three changes.
1. Enable the program to load parameters as well as save parameters.
2. Possible to change the size of data using command line arguments.
    e.g. `python main.py datalen=1000`
3. `discriminator.trainable = True,` I had to do this because learning did not progress well.  
 
This is my first pull request, so I may do strange things, but I'm sorry.

**Comment by tomoyaf** [comment]
And in my Python 3 series cPickle could not be used, so I import _pickle but this may not have been good.

**Comment by tomoyaf** [comment]
I modified it as follows
```
try:
    import cPickle as pickle
except ImportError:
    import pickle
```

**Pull request closed without merging**
